### PR TITLE
Random small improvements

### PR DESCRIPTION
**Pull request by ddekany**
This PR exists as these trivial PR-s are before the "Embed language server instead of starting new JVM", and I didn't want to pack them into it... See the individual commit messages.

### CODE REVIEW

**Comment by ddekany** [comment]
Maybe you can merge this one though. That's why I have separated it from the trickier PR. And I'm looking forward for you updating the README part, because my solution must be wrong.

**Comment by ddekany** [comment]
What about this?

**Comment by angelozerr** [comment]
I think we can ignore this PR?

**Comment by ddekany** [comment]
As it's part of the other PR, technically you can.

**Comment by angelozerr** [comment]
I close this PR since https://github.com/angelozerr/lsp4e-freemarker/pull/7

**Pull request merged**
